---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 32  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: "UTC"
      ADMIN_PASSWORD: "testing123!"
      SERVER_PASSWORD: "testing123!"  # Optional but recommended
      COMMUNITY: true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "CoverMyPalworld"
      SERVER_DESCRIPTION: ""
      CROSSPLAY_PLATFORMS: "(Steam,Xbox,PS5,Mac)"
    volumes:
      - ./palworld:/palworld/
